@tool
extends EditorExportPlugin
class_name FKExportPlugin

## FlowKit Export Plugin
## Automatically excludes unused provider scripts from exported builds.
## Works in conjunction with the provider manifest generated by the generator.
## Only provider scripts that are actively used in event sheets are included.

const MANIFEST_PATH = "res://addons/flowkit/saved/provider_manifest.tres"

# Provider directories whose files are candidates for exclusion
const PROVIDER_DIRS: Array[String] = [
	"res://addons/flowkit/actions/",
	"res://addons/flowkit/conditions/",
	"res://addons/flowkit/events/",
	"res://addons/flowkit/behaviors/",
	"res://addons/flowkit/branches/",
]

var _excluded_paths: Dictionary = {}  # path -> true, for O(1) lookups
var _exclude_count: int = 0
var _generator = null  # FKGenerator reference for auto-generation


## Store a reference to the generator so we can auto-create the manifest.
func set_generator(gen) -> void:
	_generator = gen


func _get_name() -> String:
	return "FlowKit"


func _export_begin(features: PackedStringArray, is_debug: bool, path: String, flags: int) -> void:
	_excluded_paths.clear()
	_exclude_count = 0

	# Auto-generate manifest if it doesn't exist
	if not ResourceLoader.exists(MANIFEST_PATH):
		if _generator:
			print("[FlowKit Export] No manifest found — generating one automatically before export...")
			_generator.generate_manifest()
		else:
			push_warning("[FlowKit Export] No provider manifest found and no generator available. All provider files will be included.")
			return

	# Re-check after potential auto-generation
	if not ResourceLoader.exists(MANIFEST_PATH):
		push_warning("[FlowKit Export] Manifest generation failed. All provider files will be included.")
		return

	var manifest: Resource = load(MANIFEST_PATH)
	if not manifest:
		push_warning("[FlowKit Export] Failed to load provider manifest. All provider files will be included.")
		return

	var excluded: Array = manifest.get("excluded_script_paths") if manifest.get("excluded_script_paths") else []
	if excluded.is_empty():
		print("[FlowKit Export] Manifest has no excluded providers — all providers are in use.")
		return

	for script_path in excluded:
		_excluded_paths[script_path] = true
		# Also exclude the corresponding .uid file
		var uid_path: String = script_path + ".uid"
		_excluded_paths[uid_path] = true
		# Also exclude any .import file
		var import_path: String = script_path + ".import"
		_excluded_paths[import_path] = true

	print("[FlowKit Export] Will exclude %d unused provider scripts from build." % excluded.size())


func _export_file(path: String, type: String, features: PackedStringArray) -> void:
	if _excluded_paths.has(path):
		# Skip this file — it's an unused provider
		skip()
		_exclude_count += 1


func _export_end() -> void:
	if _exclude_count > 0:
		print("[FlowKit Export] Excluded %d unused provider files from build." % _exclude_count)
	_excluded_paths.clear()
	_exclude_count = 0
